# Generated by Django 3.2.8 on 2021-12-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelpages', '0002_customer_cust_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
