# Generated by Django 3.2.8 on 2021-12-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelpages', '0003_trip_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cust_trips',
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_trips',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='travelpages.trip'),
            preserve_default=False,
        ),
    ]
