# Generated by Django 3.2.8 on 2021-12-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelpages', '0004_auto_20211213_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cust_trips',
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_trips',
            field=models.ManyToManyField(blank=True, to='travelpages.Trip'),
        ),
    ]
