# Generated by Django 3.2.8 on 2021-12-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelpages', '0005_auto_20211213_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplanet',
            name='main_photo',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_trips',
            field=models.ManyToManyField(blank=True, related_name='customer_trips', to='travelpages.Trip'),
        ),
    ]
