# Generated by Django 3.2.8 on 2021-12-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    operations = [
        migrations.AddField(
            model_name='customer',
            name='main_photo',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
